<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class CreateGradeRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' => 'required',
            'teacher' => 'required|alpha',
        ];
    }
    public function messages()
    {
        return [
            'name.required' => 'Please provide a valid grade name.',
            'teacher.required' => 'Please provide a valid teacher name.',
            'teacher.alpha' => 'Name must be a string.',
        ]; // TODO: Change the autogenerated stub
    }
}
