<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class CreateKidRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' => 'required | string',
            'phone' => 'required | numeric',
            'address' => 'required'
        ];
    }
    public function messages()
    {
        return [
            'name.required' => 'Please provide a valid kid name.',
            'phone.required' => 'Please provide a valid phone.',
            'address.required' => 'Please provide a valid address.',
            'name.string' => 'Name must be a string.',
            'phone.numeric' => 'Phone must be a number.'
        ]; // TODO: Change the autogenerated stub
    }
}
